[dc]
192.168.200.10

[server]
192.168.200.20

[all:vars]
ansible_user={{ windows_user }}
ansible_password={{ windows_user_password }}
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985