---
 - name: Import GPO backup playbook
   hosts: all
   gather_facts: false

   tasks:
    - name: Import GPO
      win_gpo_import:
        backup_path: "c:\\adm\\GPO-bkp"
        gpo_name: "Custom GPO"
        domain: "lab.local"
      register: result
    - name: Show results back
      ansible.builtin.debug:
        var: result
    - name: Show GPO ID
      ansible.builtin.debug:
        msg: "Imported GPO ID is {{ result.gpo_id }}"

