---
 - name: Import GPO backup playbook
   hosts: dc
   gather_facts: false

   tasks:
     - name: Import GPO PS module
       custom_win_gpo_import:
         backup_path:
         gpo_name:
         domain:
       register: result


       

